name: Docker Image - Continuous Integration

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment for the publication'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      version:
        description: 'App version'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} 
    env:
      VERSION: ${{ inputs.version }}
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
      DOCKER_USER: ${{ vars.DOCKER_REGISTRY_USERNAME }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Image Repository
      run: echo "IMAGE_REPOSITORY=$DOCKER_REGISTRY/portal" >> $GITHUB_ENV

    - name: Login to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: |-
          ${{ env.IMAGE_REPOSITORY }}:${{ env.VERSION }}
          ${{ env.IMAGE_REPOSITORY }}:latest
    - name: Build Summary
      run: echo "### $IMAGE_REPOSITORY:$VERSION published! :rocket:" >> $GITHUB_STEP_SUMMARY
